name: orange
version: 0.0.1
author: Valor Zhong <valorzhong@gmail.com>
description: Is a WebGL based 3D engine
homepage: https://github.com/games/orange
documentation: https://github.com/games/orange

dependencies:
  browser: any
  vector_math: any
  stats: any
  unittest: any
